name: CI deploy
on:
    push:
        branches: [master]
env:
    AWS_HOST: 3.16.156.44
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with: 
                  node-version: '14.8.0'
            - name: Build Server
              env:
                  NODE_ENV: development
              run: |
                  cd server
                  npm install --frozen-lockfile
                  tsc
            - name: Build Client
              env:
                  NODE_ENV: development
              run: |
                  cd client
                  npm install --frozen-lockfile
                  npm run build
            - name: Deploy on server
              env:
                  DEPLOYMENT_KEY_B64: ${{ secrets.DEPLOYMENT_KEY_B64 }}
              run: |
                  chmod 0755 ./.github/workflows/deploy.sh;
                  ./.github/workflows/deploy.sh;